[2024-08-26T14:26:05.161-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T14:26:05.171-0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgresql_etl.load manual__2024-08-26T19:20:34.934432+00:00 [queued]>
[2024-08-26T14:26:05.177-0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgresql_etl.load manual__2024-08-26T19:20:34.934432+00:00 [queued]>
[2024-08-26T14:26:05.177-0500] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-08-26T14:26:05.190-0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load> on 2024-08-26 19:20:34.934432+00:00
[2024-08-26T14:26:05.195-0500] {standard_task_runner.py:72} INFO - Started process 26117 to run task
[2024-08-26T14:26:05.201-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'mysql_to_postgresql_etl', 'load', 'manual__2024-08-26T19:20:34.934432+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/var/folders/hk/x06l6x4x2tj6xw06th2r87h40000gn/T/tmp69acsm2m']
[2024-08-26T14:26:05.204-0500] {standard_task_runner.py:105} INFO - Job 24: Subtask load
[2024-08-26T14:26:05.246-0500] {task_command.py:467} INFO - Running <TaskInstance: mysql_to_postgresql_etl.load manual__2024-08-26T19:20:34.934432+00:00 [running]> on host jessicas-mbp.home
[2024-08-26T14:26:05.304-0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mysql_to_postgresql_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T19:20:34.934432+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-26T19:20:34.934432+00:00'
[2024-08-26T14:26:05.305-0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T14:26:05.327-0500] {base.py:84} INFO - Retrieving connection 'postgres'
[2024-08-26T14:26:05.330-0500] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/etl_mysql_postgsql/airflow/dags/test.py", line 67, in load
    conn = pg_hook.get_conn()
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: nodename nor servname provided, or not known

[2024-08-26T14:26:05.366-0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=mysql_to_postgresql_etl, task_id=load, run_id=manual__2024-08-26T19:20:34.934432+00:00, execution_date=20240826T192034, start_date=20240826T192605, end_date=20240826T192605
[2024-08-26T14:26:05.377-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T14:26:05.377-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task load (could not translate host name "postgres" to address: nodename nor servname provided, or not known
; 26117)
Traceback (most recent call last):
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/jessicamarzin/Desktop/data_science/etl_mysql_postgsql/airflow/dags/test.py", line 67, in load
    conn = pg_hook.get_conn()
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/jessicamarzin/Desktop/data_science/test_etl/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: nodename nor servname provided, or not known

[2024-08-26T14:26:05.422-0500] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-26T14:26:05.435-0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T14:26:05.435-0500] {local_task_job_runner.py:240} INFO - ::endgroup::
