[2024-08-27T00:48:30.553+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgresql_etl.extract manual__2024-08-27T00:48:28.633642+00:00 [queued]>
[2024-08-27T00:48:30.565+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgresql_etl.extract manual__2024-08-27T00:48:28.633642+00:00 [queued]>
[2024-08-27T00:48:30.565+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-27T00:48:30.585+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract> on 2024-08-27 00:48:28.633642+00:00
[2024-08-27T00:48:30.592+0000] {standard_task_runner.py:57} INFO - Started process 843 to run task
[2024-08-27T00:48:30.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgresql_etl', 'extract', 'manual__2024-08-27T00:48:28.633642+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpw4215zsn']
[2024-08-27T00:48:30.599+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask extract
[2024-08-27T00:48:30.656+0000] {task_command.py:410} INFO - Running <TaskInstance: mysql_to_postgresql_etl.extract manual__2024-08-27T00:48:28.633642+00:00 [running]> on host f00156c30bb5
[2024-08-27T00:48:30.770+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgresql_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T00:48:28.633642+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-27T00:48:28.633642+00:00'
[2024-08-27T00:48:30.784+0000] {base.py:73} INFO - Using connection ID 'mysql_default' for task execution.
[2024-08-27T00:48:38.802+0000] {logging_mixin.py:150} INFO - Error in extract task: (2005, "Unknown MySQL server host 'local' (-3)")
[2024-08-27T00:48:38.803+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 317, in extract
    df = mysql_hook.get_pandas_df(sql=query)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 200, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 188, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'local' (-3)")
[2024-08-27T00:48:38.814+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_to_postgresql_etl, task_id=extract, execution_date=20240827T004828, start_date=20240827T004830, end_date=20240827T004838
[2024-08-27T00:48:38.827+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task extract ((2005, "Unknown MySQL server host 'local' (-3)"); 843)
[2024-08-27T00:48:38.849+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-08-27T00:48:38.876+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
